Source/BlogWebsite.Administration/Controllers/StoryContentController.cs
using BlogWebsite.Administration.Models.ViewModel;
using BlogWebsite.Data.Business.Stories;
using BlogWebsite.Data.Models.Stories;
using Microsoft.Security.Application;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsite.Administration.Controllers
{
    public class StoryContentController : Controller
    {
        StoryContentBusiness storyContentBusiness;

        public StoryContentController()
        {
            storyContentBusiness = new StoryContentBusiness();
        }

        [HttpGet]
        public ActionResult Insert()
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Read = "active"
            };
            ViewBag.menuVM = menuVM;

            return View();
        }

        [HttpPost]
        public ActionResult Insert(StoryContentVM storyContentVM)
        {
            var sanitizedHtml = Sanitizer.GetSafeHtmlFragment(storyContentVM.Content);
            int storyId = (int)Session["StoryId"];

            storyContentBusiness.Insert(new StoryContent()
            {
                StoryId = storyId,
                ChapterName = storyContentVM.ChapterName,
                Content = sanitizedHtml
            });

            return RedirectToAction("Contents", "Story", new { id = storyId });
        }

        [HttpGet]
        public ActionResult Update(long Id)
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Read = "active"
            };
            ViewBag.menuVM = menuVM;

            StoryContent storyContent = storyContentBusiness.GetById(Id);
            StoryContentVM storyContentVM = new StoryContentVM()
            {
                Id = storyContent.Id,
                StoryId = storyContent.StoryId,
                ChapterName = storyContent.ChapterName,
                Content = storyContent.Content
            };

            return View(storyContentVM);
        }

        [HttpPost]
        public ActionResult Update(StoryContentVM storyContentVM)
        {
            int storyId = (int)Session["StoryId"];

            storyContentBusiness.Update(new StoryContent()
            {
                Id = storyContentVM.Id,
                StoryId = storyId,
                ChapterName = storyContentVM.ChapterName,
                Content = storyContentVM.Content
            });
            return RedirectToAction("Contents", "Story", new { id = storyId });
        }

        [HttpGet]
        public ActionResult Delete(long Id)
        {
            storyContentBusiness.Delete(Id);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult MultipleDelete()
        {
            return RedirectToAction("Contents", "Story");
        }

        [HttpGet]
        public ActionResult Watch(long Id)
        {
            StoryContent storyContent = storyContentBusiness.GetById(Id);
            StoryContentVM storyContentVM = new StoryContentVM()
            {
                ChapterName = storyContent.ChapterName,
                Content = storyContent.Content
            };

            return PartialView(storyContentVM);
        }
    }
}

Source/BlogWebsite.Administration/Controllers/StoryController.cs
using BlogWebsite.Administration.Models.ViewModel;
using BlogWebsite.Data.Business.Stories;
using BlogWebsite.Data.Models.Stories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsite.Administration.Controllers
{
    public class StoryController : Controller
    {
        StoryTypeBusiness storyTypeBusiness;
        StoryBusiness storyBusiness;
        StoryContentBusiness storyContentBusiness;

        public StoryController()
        {
            storyTypeBusiness = new StoryTypeBusiness();
            storyBusiness = new StoryBusiness();
            storyContentBusiness = new StoryContentBusiness();
        }

        [HttpGet]
        public ActionResult Index()
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Read = "active"
            };
            return View(menuVM);
        }

        [HttpPost]
        public JsonResult Search(string keyword)
        {
            return Json(storyBusiness.Search(keyword), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Insert()
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Read = "active"
            };
            ViewBag.menuVM = menuVM;

            List<SelectListItem> lstStoryType = new List<SelectListItem>();

            foreach (var item in storyTypeBusiness.GetAll())
            {
                lstStoryType.Add(new SelectListItem() { Text = item.StoryTypeName, Value = item.Id.ToString() });
            }
            ViewBag.lstStoryType = lstStoryType;

            return View();
        }

        [HttpPost]
        public ActionResult Insert(HttpPostedFileBase Picture, StoryVM story)
        {
            string pictureName = "";

            if (Picture != null && Picture.ContentLength > 0)
            {
                pictureName = Picture.FileName;
                string filepath = Path.Combine(Server.MapPath("~/Assets/Upload/Story"), pictureName);
                Picture.SaveAs(filepath);
            }

            storyBusiness.Insert(new Story()
            {
                StoryTypeId = story.StoryTypeId,
                StoryName = story.StoryName,
                Author = story.Author,
                ChapterNumber = story.ChapterNumber,
                Introduction = story.Introduction,
                Picture = pictureName,
                Status = story.Status
            });

            return RedirectToAction("Index", "Story");
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Read = "active"
            };
            ViewBag.menuVM = menuVM;
            ViewBag.lstStoryType = storyTypeBusiness.GetAll();

            Story story = storyBusiness.GetById(Id);
            StoryVM storyVM = new StoryVM()
            {
                Id = story.Id,
                StoryTypeId = story.StoryTypeId,
                StoryName = story.StoryName,
                Author = story.Author,
                ChapterNumber = story.ChapterNumber,
                Introduction = story.Introduction,
                Picture = story.Picture,
                Status = story.Status
            };

            return View(storyVM);
        }

        [HttpPost]
        public ActionResult Update(HttpPostedFileBase Picture, StoryVM story)
        {
            string pictureName = "";

            if (Picture != null && Picture.ContentLength > 0)
            {
                pictureName = Picture.FileName;
                string filepath = Path.Combine(Server.MapPath("~/Assets/Upload/Story"), pictureName);
                Picture.SaveAs(filepath);
            }

            if (pictureName == "")
            {
                storyBusiness.UpdateExceptPicture(new Story()
                {
                    Id = story.Id,
                    StoryTypeId = story.StoryTypeId,
                    StoryName = story.StoryName,
                    Author = story.Author,
                    ChapterNumber = story.ChapterNumber,
                    Introduction = story.Introduction,
                    Status = story.Status
                });
            }
            else
            {
                storyBusiness.Update(new Story()
                {
                    Id = story.Id,
                    StoryTypeId = story.StoryTypeId,
                    StoryName = story.StoryName,
                    Author = story.Author,
                    ChapterNumber = story.ChapterNumber,
                    Introduction = story.Introduction,
                    Picture = pictureName,
                    Status = story.Status
                });
            }

            return RedirectToAction("Index", "Story");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            storyBusiness.Delete(Id);
            return RedirectToAction("Index", "Story");
        }

        [HttpGet]
        public ActionResult MultipleDelete()
        {
            return RedirectToAction("Index", "Story");
        }

        [HttpGet]
        public ActionResult Contents(int Id)
        {
            Session["StoryId"] = Id;
            Session["StoryName"] = storyBusiness.GetById(Id).StoryName;

            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Read = "active"
            };
            return View(menuVM);
        }

        [HttpPost]
        public JsonResult Contents_Index(string keyword)
        {
            int storyId = (int)Session["StoryId"];
            return Json(storyContentBusiness.Search(storyId, keyword), JsonRequestBehavior.AllowGet);
        }
    }
}

Source/BlogWebsite.Administration/Views/Story/Contents.cshtml
@model BlogWebsite.Administration.Models.ViewModel.MenuVM
@{
    ViewBag.Title = "Nội dung truyện";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<style>

    /*Căn chữ trên header*/
    .k-grid-header th.k-header {
        vertical-align: top;
    }

    .k-header .k-link {
        text-align: center;
        font-size: 16px;
        font-weight: bold;
    }

    .colorLink {
        color: #5A738E;
    }
</style>


@Html.Partial("_MenuPartialView", Model)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">@Session["StoryName"]</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách chương</h3>
                <div class="card-tools">
                    <form>
                        <button type="submit" class="btn btn-sm btn-primary" formaction="@Url.Action("Insert", "StoryContent", new { Id = ViewBag.StoryId })"><i class="fa fa-plus"></i>&nbsp;&nbsp;Thêm mới</button>
                        <button type="submit" class="btn btn-sm btn-dark" style="margin-left:10px;margin-right:5px;" formaction="@Url.Action("MultipleDelete", "StoryContent")"><i class="fa fa-eraser"></i>&nbsp;&nbsp;Xóa</button>
                    </form>
                </div>
            </div>
            <div class="card-body">

                <!--Textbox Tìm kiếm-->
                <div class="input-group fa-pull-right" style="width:250px;">
                    <input type="text" id="txtSearch" placeholder="Tìm kiếm" class="form-control">
                    <div class="input-group-btn">
                        <button id="btnSearch" type="button" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </div>
                </div>

                <div class="clearfix" style="margin-bottom: 10px;"></div>

                <div id="gridStoryContent"></div>

            </div>

        </div>

    </section>

</div>

<!------------------------------- Tạo một popup cho phần Detail ------------------------------->
<div id="detailPopup">

    <div id="popup_Container"></div>
    <hr />

    <button style="width: 50px;" class="btn btn-dark fa-pull-right" type="button" id="btnCancelPopup">Đóng</button>

</div>

<div id="deleteConfirm">

    <h4>Bạn có chắc là muốn xóa không?</h4>
    <hr />

    <button style="width: 50px; margin-left:50px;" class="btn btn-primary fa-pull-left" type="button" id="btnAgreePopup">Đồng ý</button>
    <button style="width: 50px; margin-right:50px;" class="btn btn-dark fa-pull-right" type="button" id="btnExitPopup">Thoát</button>

</div>


<!-- Template for modify column -->
<script id="modifyTemplateStoryContent" type="text/x-kendo-template">

    <div class="text-center">
        <a href="/StoryContent/Update/#=id#" title='Sửa'><i class="fas fa-edit"></i></a> |
        <a href="javascript:void(0)" title="Xem nội dung" data-StoryContentId="#=id#" onclick="ShowDetailBook(this);"><i class="fas fa-eye"></i></a> |
        <a href='javascript:void(0)' title='Xóa' data-StoryContentId="#=id#" onclick="btnDelete(this);"><i class="fas fa-trash"></i></a>
    </div>

</script>


<script src="~/App/Story/IndexStoryContent.js"></script>

Source/BlogWebsite.Administration/Views/Story/Index.cshtml
@model BlogWebsite.Administration.Models.ViewModel.MenuVM
@{
    ViewBag.Title = "Quản lý truyện";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<style>

    /*Căn chữ trên header*/
    .k-grid-header th.k-header {
        vertical-align: top;
    }

    .k-header .k-link {
        text-align: center;
        font-size: 16px;
        font-weight: bold;
    }

    .colorLink {
        color: #5A738E;
    }
</style>


@Html.Partial("_MenuPartialView", Model)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản lý truyện</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách truyện</h3>
                <div class="card-tools">
                    <form>
                        <button type="submit" class="btn btn-sm btn-primary" formaction="@Url.Action("Insert", "Story")"><i class="fa fa-plus"></i>&nbsp;&nbsp;Thêm mới</button>
                        <button type="submit" class="btn btn-sm btn-dark" style="margin-left:10px;margin-right:5px;" formaction="@Url.Action("MultipleDelete", "Story")"><i class="fa fa-eraser"></i>&nbsp;&nbsp;Xóa</button>
                    </form>
                </div>
            </div>
            <div class="card-body">

                <!--Textbox Tìm kiếm-->
                <div class="input-group fa-pull-right" style="width:250px;">
                    <input type="text" id="txtSearch" placeholder="Tìm kiếm" class="form-control">
                    <div class="input-group-btn">
                        <button  id="btnSearch" type="button" class="btn btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                </div>

                <div class="clearfix" style="margin-bottom: 10px;"></div>

                <div id="gridStory"></div>

            </div>

        </div>

    </section>

</div>

<!-- Template for modify column -->
<script id="modifyTemplateStory" type="text/x-kendo-template">

    <div class="text-center">
        <a href="/Story/Contents/#=id#" title='Cập nhật nội dung'><i class="fas fa-briefcase"></i></a> |
        <a href="/Story/Update/#=id#" title='Sửa'><i class="fas fa-edit"></i></a> |
        <a href='/Story/Delete/#=id#' title='Xóa'><i class="fas fa-trash"></i></a>
    </div>

</script>


<script src="~/App/Story/IndexStory.js"></script>

Source/BlogWebsite.Administration/Views/Story/Insert.cshtml
@model BlogWebsite.Administration.Models.ViewModel.StoryVM
@{
    /**/

    ViewBag.Title = "Thêm mới truyện";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
    var menuVM = ViewBag.menuVM as BlogWebsite.Administration.Models.ViewModel.MenuVM;
}


@Html.Partial("_MenuPartialView", menuVM)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản lý truyện</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Thêm mới truyện</h3>
            </div>
            @using (Html.BeginForm("Insert", "Story", FormMethod.Post, new { enctype = "Multipart/form-data" }))
            {
                <div class="card-body">
                    <div class="form-group" style="width:30%">
                        <label for="txtChapterIndex">Thể loại truyện</label>
                        @Html.DropDownListFor(m => m.StoryTypeId, (IEnumerable<SelectListItem>)ViewBag.lstStoryType, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group" style="width:100%">
                        <label for="txtStoryName">Tên truyện</label>
                        @Html.EditorFor(m => m.StoryName, new { htmlAttributes = new { @id = "txtStoryName", @class = "form-control", @type = "text", @placeholder = "Nhập tên truyện" } })
                    </div>
                    <div class="form-group" style="width:30%">
                        <label for="txtAuthor">Tác giả</label>
                        @Html.EditorFor(m => m.Author, new { htmlAttributes = new { @id = "txtAuthor", @class = "form-control", @type = "text", @placeholder = "Nhập tên tác giả" } })
                    </div>
                    <div class="form-group" style="width:15%">
                        <label for="txtChapterNumber">Số chương</label>
                        @Html.EditorFor(m => m.ChapterNumber, new { htmlAttributes = new { @id = "txtChapterNumber", @class = "form-control", @type = "number", @placeholder = "Nhập số chương" } })
                    </div>
                    <div class="form-group" style="width:30%">
                        <label for="txtStatus">Trạng thái</label>
                        @Html.EditorFor(m => m.Status, new { htmlAttributes = new { @id = "txtStatus", @class = "form-control", @type = "text", @placeholder = "Nhập trạng thái truyện" } })
                    </div>
                    <div class="form-group" style="width:100%">
                        <label for="txtPicture">Ảnh minh họa</label>
                        @Html.EditorFor(m => m.Picture, new { htmlAttributes = new { @id = "txtPicture", @class = "form-control", @type = "file", @accept = "image/*", @style = "width:80%; margin-right:5px;padding:.2rem .75rem;" } })
                    </div>
                    <div class="form-group" style="width:100%">
                        <label for="txtIntroduction">Giới thiệu truyện</label>
                        <textarea class="ckeditor" name="Introduction"></textarea>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="fa-pull-right">
                        <button type="submit" class="btn btn-primary" style="width:80px;margin-right:10px;">Lưu</button>
                        <a href="/Story/Index">
                            <button type="button" class="btn btn-dark">Thoát</button>
                        </a>
                    </div>
                </div>
            }

        </div>

    </section>

</div>

Source/BlogWebsite.Administration/Views/Story/Update.cshtml
@model BlogWebsite.Administration.Models.ViewModel.StoryVM
@{
    ViewBag.Title = "Chỉnh sửa truyện";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
    var menuVM = ViewBag.menuVM as BlogWebsite.Administration.Models.ViewModel.MenuVM;
}


@Html.Partial("_MenuPartialView", menuVM)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản lý truyện</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Chỉnh sửa truyện</h3>
            </div>
            @using (Html.BeginForm("Update", "Story", FormMethod.Post, new { enctype = "Multipart/form-data" }))
            {
                <div class="card-body">
                    <div class="form-group" style="width:30%">
                        <label for="txtChapterIndex">Thể loại truyện</label>
                        @Html.DropDownListFor(m => m.StoryTypeId, new SelectList(ViewBag.lstStoryType, "Id", "StoryTypeName"), htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group" style="width:100%">
                        <label for="txtStoryName">Tên truyện</label>
                        @Html.EditorFor(m => m.StoryName, new { htmlAttributes = new { @id = "txtStoryName", @class = "form-control", @type = "text", @placeholder = "Nhập tên truyện" } })
                    </div>
                    <div class="form-group" style="width:30%">
                        <label for="txtAuthor">Tác giả</label>
                        @Html.EditorFor(m => m.Author, new { htmlAttributes = new { @id = "txtAuthor", @class = "form-control", @type = "text", @placeholder = "Nhập tên tác giả" } })
                    </div>
                    <div class="form-group" style="width:15%">
                        <label for="txtChapterNumber">Số chương</label>
                        @Html.EditorFor(m => m.ChapterNumber, new { htmlAttributes = new { @id = "txtChapterNumber", @class = "form-control", @type = "number", @placeholder = "Nhập số chương" } })
                    </div>
                    <div class="form-group" style="width:30%">
                        <label for="txtStatus">Trạng thái</label>
                        @Html.EditorFor(m => m.Status, new { htmlAttributes = new { @id = "txtStatus", @class = "form-control", @type = "text", @placeholder = "Nhập trạng thái truyện" } })
                    </div>
                    <div class="form-group" style="width:100%">
                        <label for="txtPicture">Ảnh minh họa</label>
                        <div class="form-inline">
                            @Html.EditorFor(m => m.Picture, new { htmlAttributes = new { @id = "txtPicture", @class = "form-control", @type = "file", @accept = "image/*", @style = "width:80%; margin-right:5px;padding:.2rem .75rem;" } })
                            <img src="~/Assets/Upload/Story/@Model.Picture" style="width:2.5rem; height:2.5rem" />
                        </div>
                    </div>
                    <div class="form-group" style="width:100%">
                        <label for="txtIntroduction">Giới thiệu truyện</label>
                        <textarea id="ckeditorContent" class="ckeditor" name="Introduction"></textarea>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="fa-pull-right">
                        <button type="submit" class="btn btn-primary" style="width:80px;margin-right:10px;">Lưu</button>
                        <a href="/Story/Index">
                            <button type="button" class="btn btn-dark">Thoát</button>
                        </a>
                    </div>
                </div>
            }

        </div>

    </section>

</div>

<div id="editorcontents" hidden>
    @Html.Raw(Model.Introduction)
</div>


<script>

    $(function () {
        var html = $("#editorcontents").html();
        CKEDITOR.instances['ckeditorContent'].setData(html)
    });

</script>