Source/BlogWebsite.Administration/Controllers/StoryAudioContentController.cs
using BlogWebsite.Administration.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsite.Administration.Controllers
{
    public class StoryAudioContentController : Controller
    {
        [HttpGet]
        public ActionResult Insert()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Watch(string id)
        {
            StoryAudioContentVM chapterContent = null;

            //using (MyBlogEntities entity = new MyBlogEntities())
            //{
            //    var lst = entity.SP_StoryContent_GetById(2);

            //    foreach (var item in lst)
            //    {
            //        chapterContent = new StoryAudioContentVM()
            //        {
            //            ChapterName = item.ChapterName,
            //            //Content = item.Content
            //        };
            //    }
            //}

            return PartialView(chapterContent);
        }

        [HttpPost]
        public ActionResult Insert( HttpPostedFileBase AudioPath, StoryAudioContentVM chapterContent)
        {
            try
            {
                if (AudioPath.ContentLength > 0)
                {
                    string filename = Path.GetFileName(AudioPath.FileName);
                    string path = Path.Combine(Server.MapPath("~/Assets/Upload"), filename);                    
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }


            //using (MyBlogEntities entity = new MyBlogEntities())
            //{
            //    //entity.SP_StoryContent_Insert(1, chapterContent.ChapterIndex, chapterContent.ChapterName, chapterContent.Content);
            //}

            return RedirectToAction("Contents", "StoryAudio");
        }

        [HttpGet]
        public ActionResult Update(string Id)
        {
            StoryAudioContentVM chapterContent = null;

            //using (MyBlogEntities entity = new MyBlogEntities())
            //{
            //    var lst = entity.SP_StoryContent_GetById(1);

            //    foreach (var item in lst)
            //    {
            //        chapterContent = new StoryAudioContentVM()
            //        {
            //            ChapterIndex = item.ChapterIndex,
            //            ChapterName = item.ChapterName,
            //            //Content = item.Content
            //        };
            //    }
            //}

            return View(chapterContent);
        }

        [HttpPost]
        public ActionResult Update(StoryAudioContentVM chapterContent)
        {
            return RedirectToAction("Contents", "StoryAudio");
        }

        [HttpGet]
        public ActionResult Delete(string Id)
        {
            return RedirectToAction("Contents", "StoryAudio");
        }

        [HttpGet]
        public ActionResult MultipleDelete()
        {
            return RedirectToAction("Contents", "StoryAudio");
        }

        [HttpPost]
        public string UploadProcess(HttpPostedFileBase file)
        {
            //string filePath = Server.MapPath( "~/Assets/Libs/" + file.FileName);
            string filePath = file.FileName;

            return filePath;
        }
    }
}

Source/BlogWebsite.Administration/Controllers/StoryAudioController.cs
using BlogWebsite.Administration.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsite.Administration.Controllers
{
    public class StoryAudioController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Audio = "active"
            };
            return View(menuVM);
        }

        [HttpGet]
        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(StoryAudioVM storyAudio)
        {
            return RedirectToAction("Index", "StoryAudio");
        }

        [HttpGet]
        public ActionResult Update(string Id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Update(StoryAudioVM storyAudio)
        {
            return RedirectToAction("Index", "StoryAudio");
        }

        [HttpGet]
        public ActionResult Delete(string Id)
        {
            return RedirectToAction("Index", "StoryAudio");
        }

        [HttpGet]
        public ActionResult MultipleDelete()
        {
            return RedirectToAction("Index", "StoryAudio");
        }

        [HttpGet]
        public ActionResult Contents(string Id)
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Audio = "active"
            };
            return View(menuVM);
        }
    }
}

Source/BlogWebsite.Administration/Views/StoryAudio/Contents.cshtml
@model BlogWebsite.Administration.Models.ViewModel.MenuVM
@{
    ViewBag.Title = "Nội dung truyện audio";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<style>

    /*Căn chữ trên header*/
    .k-grid-header th.k-header {
        vertical-align: top;
    }

    .k-header .k-link {
        text-align: center;
        font-size: 16px;
        font-weight: bold;
    }

    .colorLink {
        color: #5A738E;
    }
</style>


@Html.Partial("_MenuPartialView", Model)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Truyện Dế Mèn Phưu Lưu Ký</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách chương</h3>
                <div class="card-tools">
                    <form>
                        <button type="submit" class="btn btn-sm btn-primary" formaction="@Url.Action("Insert", "StoryAudioContent")"><i class="fa fa-plus"></i>&nbsp;&nbsp;Thêm mới</button>
                        <button type="submit" class="btn btn-sm btn-dark" style="margin-left:10px;margin-right:5px;" formaction="@Url.Action("MultipleDelete", "StoryAudioContent")"><i class="fa fa-eraser"></i>&nbsp;&nbsp;Xóa</button>
                    </form>
                </div>
            </div>
            <div class="card-body">

                <!--Textbox Tìm kiếm-->
                <div class="input-group fa-pull-right" style="width:250px;">
                    <input type="text" id="txtSearch" placeholder="Tìm kiếm" class="form-control">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </div>
                </div>

                <div class="clearfix" style="margin-bottom: 10px;"></div>

                <div id="gridStoryAudioContent"></div>

            </div>

        </div>

    </section>

</div>

<!------------------------------- Tạo một popup cho phần Detail ------------------------------->
<div id="detailPopup">

    <div id="popup_Container"></div>
    <hr />
    <button style="width: 50px;" class="btn btn-dark pull-right" type="button" id="btnCancelPopup">Đóng</button>

</div>


<!-- Template for modify column -->
<script id="modifyTemplateStoryAudioContent" type="text/x-kendo-template">

    <div class="text-center">
        <a href="/StoryAudioContent/Update/#=id#" title='Sửa'><i class="fas fa-edit"></i></a> |
        <a href="javascript:void(0)" title="Nghe nội dung" data-StoryAudioContentId="#=id#" data-BookName="Dế mèn phưu lưu ký" onclick="ShowDetailBook(this);"><i class="fas fa-eye"></i></a> |
        <a href='/StoryAudioContent/Delete/#=id#' title='Xóa'><i class="fas fa-trash"></i></a>
    </div>

</script>


<script src="~/App/Story/IndexStoryAudioContent.js"></script>

Source/BlogWebsite.Administration/Views/StoryAudio/Index.cshtml
@model BlogWebsite.Administration.Models.ViewModel.MenuVM
@{
    ViewBag.Title = "Quản lý truyện audio";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<style>

    /*Căn chữ trên header*/
    .k-grid-header th.k-header {
        vertical-align: top;
    }

    .k-header .k-link {
        text-align: center;
        font-size: 16px;
        font-weight: bold;
    }

    .colorLink {
        color: #5A738E;
    }
</style>


@Html.Partial("_MenuPartialView", Model)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản lý truyện audio</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách truyện audio</h3>
                <div class="card-tools">
                    <form>
                        <button type="submit" class="btn btn-sm btn-primary" formaction="@Url.Action("Insert", "StoryAudio")"><i class="fa fa-plus"></i>&nbsp;&nbsp;Thêm mới</button>
                        <button type="submit" class="btn btn-sm btn-dark" style="margin-left:10px;margin-right:5px;" formaction="@Url.Action("MultipleDelete", "StoryAudio")"><i class="fa fa-eraser"></i>&nbsp;&nbsp;Xóa</button>
                    </form>
                </div>
            </div>
            <div class="card-body">

                <!--Textbox Tìm kiếm-->
                <div class="input-group fa-pull-right" style="width:250px;">
                    <input type="text" id="txtSearch" placeholder="Tìm kiếm" class="form-control">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </div>
                </div>

                <div class="clearfix" style="margin-bottom: 10px;"></div>

                <div id="gridStoryAudio"></div>

            </div>

        </div>

    </section>

</div>

<!-- Template for modify column -->
<script id="modifyTemplateStoryAudio" type="text/x-kendo-template">

    <div class="text-center">
        <a href="/StoryAudio/Contents/#=id#" title='Cập nhật nội dung'><i class="fas fa-briefcase"></i></a> |
        <a href="/StoryAudio/Update/#=id#" title='Sửa'><i class="fas fa-edit"></i></a> |
        <a href='/StoryAudio/Delete/#=id#' title='Xóa'><i class="fas fa-trash"></i></a>
    </div>

</script>


<script src="~/App/Story/IndexStoryAudio.js"></script>