Source/BlogWebsite.Administration/Controllers/StoryComicsController.cs
using BlogWebsite.Administration.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogWebsite.Administration.Controllers
{
    public class StoryComicsController : Controller
    {
        public ActionResult Index()
        {
            MenuVM menuVM = new MenuVM()
            {
                Story = "menu-open",
                Story_Main = "active",
                Story_Comics = "active"
            };
            return View(menuVM);
        }
    }
}

Source/BlogWebsite.Administration/Views/StoryComics/Index.cshtml
@model BlogWebsite.Administration.Models.ViewModel.MenuVM
@{
    ViewBag.Title = "Quản lý truyện tranh";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<style>

    /*Căn chữ trên header*/
    .k-grid-header th.k-header {
        vertical-align: top;
    }

    .k-header .k-link {
        text-align: center;
        font-size: 16px;
        font-weight: bold;
    }

    .colorLink {
        color: #5A738E;
    }
</style>


@Html.Partial("_MenuPartialView", Model)


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản lý truyện tranh</h1>
                </div>

                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v2</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách truyện tranh</h3>
                <div class="card-tools">
                    <form>
                        <button type="submit" class="btn btn-sm btn-primary" formaction="@Url.Action("Insert", "StoryComics")"><i class="fa fa-plus"></i>&nbsp;&nbsp;Thêm mới</button>
                        <button type="submit" class="btn btn-sm btn-dark" style="margin-left:10px;margin-right:5px;" formaction="@Url.Action("MultipleDelete", "StoryComics")"><i class="fa fa-eraser"></i>&nbsp;&nbsp;Xóa</button>
                    </form>
                </div>
            </div>
            <div class="card-body">

                <!--Textbox Tìm kiếm-->
                <div class="input-group fa-pull-right" style="width:250px;">
                    <input type="text" id="txtSearch" placeholder="Tìm kiếm" class="form-control">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                </div>

                <div class="clearfix" style="margin-bottom: 10px;"></div>

                <div id="gridStoryComics"></div>

                <h2>Module đang được hoàn thiện vui lòng chờ ...!</h2>

            </div>

        </div>

    </section>

</div>

<!-- Template for modify column -->
<script id="modifyTemplateStoryComics" type="text/x-kendo-template">

    <div class="text-center">
        <a href="/Story/Contents/#=id#" title='Cập nhật nội dung'><i class="fas fa-briefcase"></i></a> |
        <a href="/Story/Update/#=id#" title='Sửa'><i class="fas fa-edit"></i></a> |
        <a href='/Story/Delete/#=id#' title='Xóa'><i class="fas fa-trash"></i></a>
    </div>

</script>


<script src="~/App/Story/IndexStory.js"></script>